[profile.default]
src = "src"
script = "scripts"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
  "@contracts-bedrock/=lib/optimism/packages/contracts-bedrock/src/",
  "createx/=lib/createx/src/",
  "@solady/=lib/optimism/packages/contracts-bedrock/lib/solady/src/"
]