[deploy_config]
salt = "ethers phoenix"

[single_chain_deploy_config]
chain = "op_chain_a"

[multi_chain_deploy_config]
chains = ["op_chain_a","op_chain_b"]

[token]
owner_address = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
name = "TestSuperchainERC20"
symbol = "TSU"
decimals = 18
